language: csharp
solution: ConsoleApplication4/ConsoleApplication4.sln
install:
  - nuget restore csharp-extensions.sln
  - nuget install xunit.runners -Version 2.0.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release csharp-extensions.sln
  - mono ./testrunner/xunit.runners.2.0.0/tools/xunit.console.exe ./csharp-extensions-test/bin/Release/csharp-extensions-tests.dll
notifications:
  email: false